# Site settings
title: Brian Dame - Software Engineer
email: foo@bar.com
description: > # this means to ignore newlines until "baseurl:"
  Brian Dame - Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://briandame.github.io" # the base hostname & protocol for your site
twitter_username: briandame
github_username:  briandame

# Build settings
markdown: kramdown
